#!/bin/bash
grep -H "<h" $1 | \
sed -e"s/\([a-z-]*\)-\([0-9]*\).md:<a href=\"\(#heading--[A-Za-z0-9-]*\)\"><h[2-5] id=\"heading--[A-Za-z0-9-]*\">\([^\<]*\)<\/h[2-5]><\/a>/[\4](\/t\/\1\/\2\3)/" | \
sed -e"s/About //g" |\
sed -e"s/about //g" |\
sed -e"s/The //g" | \
sed -e"s/the //g"
