#!/bin/sh

sqlite3 /etc/rad/rad.db 'select * from links' \
    | grep "/${1%%.*}|" \
    | grep -v "2\.7" \
    | grep -v "2\.8" \
    | cut -f2,3 -d"|" \
    | cut -f3- -d"/" \
    | sed -e 's/|/ /g' \
    | sed -e 's/^/\//' \
    | sed -e 's/i\//i /' \
    | awk '{print  "cat " $2 ".md | radf -b rad-begin -e rad-end -s " $1 " | radRlink -s " $1 " | radRmenu -b " $2 " | radput -t " $3}' > /tmp/Rmake.sh
sqlite3 /etc/rad/rad.db 'select * from links' \
    | grep "/${1%%.*}|" \
    | grep -v "2\.7" \
    | grep -v "2\.8" \
    | cut -f2,3 -d"|" \
    | cut -f3- -d"/" \
    | sed -e 's/|/ /g' \
    | sed -e 's/^/\//' \
    | sed -e 's/i\//i /' \
    | awk '{print  "cat " $2 ".md | radf -b rad-begin -e rad-end -s " $1 " | radRlink -s " $1 " | markdown | sed -e \"s/\\[\\/*note[A-Za-z \\\"]*\\]//g\" | sed -e  \"s/href=\\\"\\/t\\/\\([^\\/]*\\)\\/[0-9]*/href=\\\"\\1.html/g\" > /tmp/publication-staging" $1 "/html/" $2 ".html"}' >> /tmp/Rmake.sh
chmod 777 /tmp/Rmake.sh
/tmp/Rmake.sh
#rm /tmp/Rmake.sh
#| sed -e \"s/\\[\\/*note[A-Za-z\\" ]*\\]//g\" 
#\"s/href=\\\"\\/t\\/\\(\\[a-zA-Z0-9-\\]*\\)\\/\\[0-9\\]*/href=\\\"https:\\/\\/$1.html/g\"
