#!/bin/sh

rm /tmp/Rmake.sh
sqlite3 ~/.config/rad/rad.db 'select * from links' \
    | grep "/${1%%.*}|" \
    | grep -v "2\.7" \
    | grep -v "2\.8" \
    | cut -f2,3 -d"|" \
    | cut -f3- -d"/" \
    | sed -e 's/|/ /g' \
    | sed -e 's/^/\//' \
    | sed -e 's/i\//i /' \
    | awk -v title=$1 '{print  "cat " $2 ".md | radfilter -b rad-begin -e rad-end -s " $1 " | radlink -s " $1 " | rad2html -t title -f " $2 " > ~/.local/publication-staging" $1 "/html/" $2 ".html"}' >> /tmp/Rmake.sh
chmod 777 /tmp/Rmake.sh
/tmp/Rmake.sh
# cp ~/.local/publication-staging/deb/3.1/cli/html/*.html production-html-deb/cli
# cp ~/.local/publication-staging/snap/3.1/cli/html*.html production-html-snap/cli
# cp ~/.local/publication-staging/deb/3.1/ui/html/*.html production-html-deb/ui
# cp ~/.local/publication-staging/snap/3.1/ui/html/*.html production-html-snap/ui
# cp /tmp/images/* production-html-deb/images
# cp /tmp/images/* production-html-deb/cli/images
# cp /tmp/images/* production-html-deb/ui/images
# cp /tmp/images/* production-html-snap/images
# cp /tmp/images/* production-html-snap/cli/images
# cp /tmp/images/* production-html-snap/ui/images
# cp ~/.local/publication-staging/snap/3.1/ui/html/maas-documentation-25.html production-html-snap
# cp ~/.local/publication-staging/deb/3.1/ui/html/maas-documentation-25.html production-html-deb
# cp ~/.local/publication-staging/snap/3.1/ui/html/maas-documentation-25.html production-html-snap/maas-documentation.html
# cp ~/.local/publication-staging/deb/3.1/ui/html/maas-documentation=25.html production-html-deb/maas-documentation.html
